name: nook
version: 0.0.1

environment:
  sdk: ^2.7.0

dependencies:
  firebase: ^5.0.0
  uuid: ^2.0.0
  http: ^0.12.0
  intl: ^0.16.0

dev_dependencies:
  build_runner: ^1.7.0
  build_web_compilers: ^2.6.0
